# Generated by Django 5.1.4 on 2025-05-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="anomalies",
            field=models.ManyToManyField(
                blank=True, related_name="tickets", to="tickets.typeanomalie"
            ),
        ),
        migrations.AddField(
            model_name="typeanomalie",
            name="est_personnalisee",
            field=models.BooleanField(default=False),
        ),
    ]
