# Generated by Django 5.2 on 2025-05-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducteur',
            name='heures_travaillees',
            field=models.FloatField(default=0),
        ),
    ]
