# Generated by Django 5.2 on 2025-05-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_conducteur_heures_travaillees'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducteur',
            name='heure_de_fin_du_conteur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
