# Generated by Django 5.1.7 on 2025-05-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_utilisateur_assigne_maintenance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="heure_creation",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
