# Generated by Django 5.1.4 on 2025-05-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_anomalies_typeanomalie_est_personnalisee"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="anomalies_personnalisees",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="typeanomalie",
            name="est_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="gravite",
            field=models.CharField(
                choices=[
                    ("LEGERE", "Légère"),
                    ("MOYENNE", "Moyenne"),
                    ("GRAVE", "Grave"),
                    ("CRITIQUE", "Critique"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="reference",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="statut",
            field=models.CharField(
                choices=[
                    ("NOUVEAU", "Nouveau"),
                    ("EN_COURS", "En cours"),
                    ("RESOLU", "Résolu"),
                    ("CLOTURE", "Clôturé"),
                ],
                default="NOUVEAU",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="typeanomalie",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="typeanomalie",
            name="gravite_par_defaut",
            field=models.CharField(
                choices=[
                    ("LEGERE", "Légère"),
                    ("MOYENNE", "Moyenne"),
                    ("GRAVE", "Grave"),
                    ("CRITIQUE", "Critique"),
                ],
                default="MOYENNE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="typeanomalie",
            name="identifiant",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="typeanomalie",
            name="type_vehicule_concerne",
            field=models.CharField(
                choices=[("CAMION", "Camion"), ("MACHINE", "Machine")], max_length=50
            ),
        ),
    ]
