# Generated by Django 5.1.7 on 2025-05-23 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_alter_ticket_heure_creation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicule",
            name="date_mise_en_service",
        ),
        migrations.RemoveField(
            model_name="vehicule",
            name="marque",
        ),
        migrations.RemoveField(
            model_name="vehicule",
            name="matricule",
        ),
        migrations.RemoveField(
            model_name="vehicule",
            name="tonnage_max",
        ),
        migrations.AddField(
            model_name="arretvehicule",
            name="taus_disponibilite",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="arretvehicule",
            name="taux_utilisation",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="heure_creation",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="typeanomalie",
            name="type_vehicule_concerne",
            field=models.CharField(
                choices=[
                    ("CAMION", "Camion"),
                    ("MACHINE", "Machine"),
                    ("ENGINS", "Engins"),
                    ("BULL", "Bull"),
                ],
                max_length=50,
            ),
        ),
    ]
