# Generated by Django 5.1.4 on 2025-05-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_ticket_anomalies_personnalisees_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conducteur",
            name="utilisateur",
        ),
    ]
