# Generated by Django 5.2 on 2025-05-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_conducteur_heure_de_fin_du_conteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducteur',
            name='heure_de_fin_du_conteur',
            field=models.FloatField(default=0),
        ),
    ]
