# Generated by Django 5.1.4 on 2025-05-06 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_remove_conducteur_utilisateur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="date_creation",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
